/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  menuSidebar: ['menu'],
  AideMemoireSidebar: [{type: 'autogenerated', dirName: 'Aide-memoire'}],
  AlgorithmesSidebar: [{type: 'autogenerated', dirName: 'Algorithmes'}],
  CodecademySidebar: [{type: 'autogenerated', dirName: 'Codecademy'}],
  freeCodeCampSidebar: [{type: 'autogenerated', dirName: 'freeCodeCamp'}],
  openClassroomsSidebar: [{type: 'autogenerated', dirName: 'OpenClassrooms'}],
  UdemySidebar: [{type: 'autogenerated', dirName: 'Udemy'}],
  CodewarsSidebar: [{type: 'autogenerated', dirName: 'Codewars'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};
